### ISSUE TITLE
Code review UGC sprint 2

### ISSUE THREAD

**Issue by BigDeepBlue** [SRSamoylenko/ugc_sprint_1#25]
Привет! У вас хорошо оформлены исследования по выбору БД, но есть пара моментов, которые надо поправить:

1. ~~По UGC-API, вы возможно не до конца увидели разницу между этим спринтом и предыдущим. В прошлом спринте мы создавали хранилище для "холодных" UGC-данных пользователя. То есть мы собирали инфу для наших аналитиков, которую конечный юзер никогда не увидит и не будет использовать. В этом спринте мы собираем похожие данные, но необходимые самому пользователю. Например, лайки и закладки - это теперь про управление ими самим пользователем. То есть, например, по лайкам у вас должен быть полный CRUD - пользователь должен иметь возможность не только поставить лайк или получить список лайков, но и его отменить. Давайте реализуем такие эндпоинты для лайков или закладок. Вам будет так же нужен новый сервис, который будет сразу писать в mongo или другое хранилище, ведь иначе у юзера поедет интерфейс, если вы его запросы будете через kafka и ETL асинхронно перекладывать (пока вы будете копить n-ивентов в шине для обработки). Из асинхронных либ для монго есть только это: https://motor.readthedocs.io/en/stable/~~
2. ~~[Тут](https://github.com/SRSamoylenko/ugc_sprint_1/blob/ab95229f814416001ff489268a1bcc1530ec1064/test_db/test_mongo/generate_data.py#L37) уже достаточная простыня кода, стоит ее разбить на функции~~
3. ~~Можно лучше: [ссылка](https://github.com/SRSamoylenko/ugc_sprint_1/blob/ab95229f814416001ff489268a1bcc1530ec1064/.github/workflows/python.yml#L66) на репо может поменяться, имеет смысл ее тоже собирать из переменных пайплайна~~
4. ~~По sentry: давайте занесем [эту](https://github.com/SRSamoylenko/ugc_sprint_1/blob/ab95229f814416001ff489268a1bcc1530ec1064/api/src/app.py#L19) часть под `if settings.sentry_dsn`, чтобы иметь возможность отключить отправку в sentry в тех же тестах~~
5. ~~Вы пропустили в [доке](https://docs.sentry.io/platforms/python/configuration/sampling/#setting-a-uniform-sample-rate) sentry, что [этот](https://github.com/SRSamoylenko/ugc_sprint_1/blob/ab95229f814416001ff489268a1bcc1530ec1064/api/src/app.py#L24) параметр нельзя оставлять равным 1. А я рекомендую вообще его не указывать, либо задавать равным нулю, либо перенести опять же в конфиг. Почему? Потому что это не про рейт отправки ошибок. А про транзакции, а транзакции - это аналог средств мониторинга вроде statsd, telegraf and etc. То есть разработчики sentry запилили свою систему сбора метрик, но она откровенно говоря плохо работает под нагрузкой. У меня в компании мы как-то пробовали ее, так вот наша self-hosted sentry упала при 10% транзакций. В общем, будьте аккуратны с этим параметром.~~

**Comment by maximium** [comment]
Задание по пункту #1 выполнено в https://github.com/maximium/movies-ugc

**Comment by BigDeepBlue** [comment]
1. [Тут](https://github.com/maximium/movies-ugc/blob/ab603c44272ca5262b16f813eb085ff88b8085a1/src/services/estimations.py#L105) неверная аннотация, из метода еще `None` возвращается
2. В целом в сервисах можно было подумать над SOLID. У вас в трех файлах сервисы отличаются только [конвертацией](https://github.com/maximium/movies-ugc/blob/ab603c44272ca5262b16f813eb085ff88b8085a1/src/services/estimations.py#L114) в схемы
3. Интересная [реализация](https://github.com/maximium/movies-ugc/blob/ab603c44272ca5262b16f813eb085ff88b8085a1/src/api/v1/estimations.py#L79) в плане привязки к id конкретного события, имеющая право на жизнь..Но чисто архитектурно более просто и очевидно привязаться к связке `user_id->movie_id`, так как любое из действий (лайк, закладка, просмотр) в такой связке возможно в единственном числе. Ну и с точки зрения фронта будет проще, не нужно будет id закладки из get запроса выковыривать

Но в целом это все мелочи) Молодцы, что реализовали целиком новый сервис. Работу принимаю
